# Generated by Django 4.2.30 on 2026-09-02 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_seed_missing_providers'),
    ]

    operations = [
        migrations.AddField(
            model_name='provider',
            name='api_key',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
