# Generated by Django 4.2.30 on 2026-09-03 03:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_provider_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='provider',
            name='api_key',
        ),
        migrations.RemoveField(
            model_name='userapikey',
            name='label',
        ),
    ]
