# Generated by Django 4.2.30 on 2026-09-03 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_provider_api_key_remove_userapikey_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
