# Generated by Django 4.2.30 on 2026-09-01 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='file_key',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
