# Generated by Django 4.2.30 on 2026-09-05 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_add_file_key_remove_file_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('pdf', 'PDF'), ('docx', 'DOCX'), ('txt', 'Text'), ('csv', 'CSV'), ('md', 'Markdown'), ('xlsx', 'Excel'), ('json', 'JSON'), ('html', 'HTML')], max_length=10),
        ),
    ]
