"use client";

import SitePage from "@/components/landing/SitePage";

const sections: { title: string; paragraphs: string[] }[] = [
  {
    title: "Acceptance",
    paragraphs: [
      "By creating an account or using NextMind, you agree to these terms. If you use the service on behalf of an organization, you confirm you are authorized to bind that organization.",
    ],
  },
  {
    title: "The service",
    paragraphs: [
      "NextMind provides a hosted workspace to upload documents, organize them into collections, and chat over them using third-party AI models. Retrieval combines semantic embeddings, keyword search, fusion, and reranking; answers include source citations where available.",
      "AI-generated answers can be wrong. Citations are provided so you can verify important claims against the original documents before relying on them.",
    ],
  },
  {
    title: "Accounts",
    paragraphs: [
      "You must provide an accurate email address and keep your credentials confidential. You are responsible for activity under your account. We may suspend accounts that abuse the service or violate these terms.",
    ],
  },
  {
    title: "Acceptable use",
    paragraphs: [
      "You agree not to upload content you have no right to process, attempt to access other users' data, interfere with the service's operation, or use the service for unlawful, harmful, or infringing purposes.",
      "Upload limits apply (supported file types, 100 MB per file, 40 files per batch). We may adjust limits to protect reliability.",
    ],
  },
  {
    title: "Third-party providers and keys",
    paragraphs: [
      "AI responses are generated by third-party providers through API keys you supply. Your use of those providers is governed by their terms, pricing, and rate limits — including any free-tier restrictions.",
      "You are responsible for safeguarding your keys and for charges incurred on your provider accounts. Revoking a key in the provider's console immediately stops our access.",
    ],
  },
  {
    title: "Availability and changes",
    paragraphs: [
      "We aim for reliable service but do not guarantee uninterrupted availability. Features, supported file types, and provider integrations may change as the product evolves; we will communicate material changes in advance where reasonable.",
    ],
  },
  {
    title: "Liability",
    paragraphs: [
      "To the maximum extent permitted by law, the service is provided “as is” without warranties of any kind, and our liability is limited to the amounts you paid us (if any) in the 12 months before the claim. We are not liable for the accuracy of AI-generated content or for third-party provider outages.",
    ],
  },
  {
    title: "Termination",
    paragraphs: [
      "You may stop using the service and delete your account at any time, which removes your data as described in the privacy policy. We may suspend or terminate accounts that violate these terms.",
    ],
  },
  {
    title: "Contact",
    paragraphs: [
      "Questions about these terms: support@nextmind.ai.",
    ],
  },
];

export default function TermsPage() {
  return (
    <SitePage>
      <section className="pt-36 pb-10">
        <div className="mx-auto max-w-[760px] px-5">
          <p className="text-[12px] font-semibold tracking-[0.2em] text-[#2A7D5F] uppercase mb-3">
            Terms of service
          </p>
          <h1 className="text-[36px] md:text-[44px] font-semibold tracking-tight text-[#0D2B22] mb-3">
            Fair terms, plain language
          </h1>
          <p className="text-[13px] text-[#0D2B22]/55">Last updated: September 2026</p>
        </div>
      </section>
      <section className="pb-20">
        <div className="mx-auto max-w-[760px] px-5 space-y-8">
          {sections.map((s) => (
            <div
              key={s.title}
              className="rounded-2xl border border-[#0D2B22]/10 bg-white/70 backdrop-blur-xl p-6 md:p-8"
            >
              <h2 className="text-[18px] font-semibold text-[#0D2B22] mb-3">{s.title}</h2>
              <div className="space-y-3">
                {s.paragraphs.map((p, i) => (
                  <p key={i} className="text-[14px] leading-relaxed text-[#0D2B22]/70">{p}</p>
                ))}
              </div>
            </div>
          ))}
        </div>
      </section>
    </SitePage>
  );
}
